# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(help_text="What is the project's anticipated (or actual) start date?")),
                ('end', models.DateField(help_text='What is the PoP of the funding? (expiration)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned', models.BooleanField(default=True)),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('opportunity', 'Opportunity'), ('pending', 'Pending'), ('active', 'Active'), ('close-out', 'Close Out'), ('archived', 'Archived')], max_length=12)),
                ('start', models.DateField(help_text="What is the project's anticipated (or actual) start date?")),
                ('end', models.DateField(help_text="What is the project's anticipated (or actual) end date?")),
                ('deliverables', models.ManyToManyField(to='crm.Deliverable')),
                ('predecessor', models.ForeignKey(blank=True, help_text='If this project is a follow-on from another project, select that project here.', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Sponsor'),
        ),
    ]
